---
- hosts: all
  become: yes
  gather_facts: yes
  tasks:
  - import_role:
      name: common

- hosts: frontends
  become: yes
  gather_facts: no
  tasks:
  - import_role:
      name: deploy_haproxy

- hosts: apps
  become: yes
  gather_facts: no
  tasks:
  - import_role:
      name: deploy_tomcat

- hosts: appdbs
  become: yes
  vars_files:
    - vars/main.yml
  tasks:
  - import_role:
      name: geerlingguy.postgresql
